### ISSUE TITLE
Expanded Singles have noticeably different styling

### ISSUE THREAD

**Issue by jamiewade** [engram-design/ExpandedSingles#23]
### Description

![Screenshot_2020-02-19 Entries - Craft 3 Framework(1)](https://user-images.githubusercontent.com/6672331/74829114-360eba00-5308-11ea-8ac9-29233f07cadd.png)

All entries, Pages, News, and News Tags are all core Craft and core Sections.

Homepage, Page Not Found (404), Search Results, and Sitemap are expanded Singles, and the font-weight looks _slightly_ heavier.

### Additional info

- Plugin version: 1.0.9
- Craft version: 3.4.6.1
- Browser: Firefox 73.0.1 (64-bit)

**Comment by engram-design** [comment]
Yep, its a known thing. The behaviour now adds an overlay to the button, to prevent overwriting behaviour when you'd normally click a menu item. Mostly to get multi-site filtering working effectively.

I didn't want to have to do version-specific changes for Craft 3.3 and 3.4, but I will at some point to match the styles up seamlessly. Its really just because the text for the sidebar has an alpha channel.

**Comment by jamiewade** [comment]
Great, thanks for the explanation. And sure, it's only a minor thing really, just felt the need to create an issue for the record.

**Comment by engram-design** [comment]
Yep, will sort it out at some stage, or until it really bugs someone enough to submit a PR.

**Comment by engram-design** [comment]
Updated in [1.0.10](https://github.com/verbb/expanded-singles/releases/tag/1.0.10)
